#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

resources:
  repositories:
  - repository: caching-templates
    type: github
    name: willsmythe/caching-templates
    endpoint: willsmythe

stages:
- stage: firstrun
  jobs:
  - job:
    strategy:
      matrix:
        linux:    
          VM_IMAGE: ubuntu-16.04
        windows:
          VM_IMAGE: vs2017-win2016
          CACHE_PACK_FORMAT: 7z-split
        macos:
          VM_IMAGE: macos-10.13
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - template: .azure-pipelines-steps.yml

- stage: secondrun
  jobs:
  - job:
    strategy:
      matrix:
        linux:    
          VM_IMAGE: ubuntu-16.04
        windows:
          VM_IMAGE: vs2017-win2016
          CACHE_PACK_FORMAT: 7z-split
        macos:
          VM_IMAGE: macos-10.13
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - template: .azure-pipelines-steps.yml

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # Ensures the handful of tests that should be skipped during CI are
  CI: true

  CACHE_PACK: true
  CACHE_PATH: $(Build.SourcesDirectory)/node_modules
  CACHE_KEY: |    
    jest-v10
    node_modules
    $(Agent.OS)
    $(Build.SourcesDirectory)/yarn.lock
    $(CACHE_PACK)
    $(CACHE_PACK_FORMAT)
    $(Build.BuildNumber)
