#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Windows
#    pool:
#      vmImage: 'Hosted Windows 2019 with VS2019'
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        displayName: 'Preserve LF endings and symbolic links on check out'
      - script: npm install -g yarn@1.9.4
      - script: |
          SET SrcRoot="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\"
          SET TargetRoot="C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin\"
          CALL :DEQUOTE SrcRoot
          CALL :DEQUOTE TargetRoot
          FOR /D %%A IN ("%SrcRoot%\*") DO (
            MKLINK /D "%TargetRoot%\%%~NA" "%%~A"
            )
          FOR %%A IN ("%SrcRoot%\*") DO (
            MKLINK "%TargetRoot%\%%~NXA" "%%~A"
            )                
          ECHO Linked all files and directories from MSBuild\Current\Bin to MSBuild\15.0\Bin
          GOTO EOF                
          :DEQUOTE
          FOR /F "delims=" %%A IN ('ECHO %%%1%%') DO SET %1=%%~A
          GOTO :EOF
          :EOF
      - template: .azure-pipelines-steps.yml

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      # This step can be removed once Mercurial gets installed on the macOS image. See https://github.com/Microsoft/azure-pipelines-image-generation/issues/604
      - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install mercurial
        displayName: 'Install Mercurial'
      - template: .azure-pipelines-steps.yml

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # By default, Azure Pipelines clones to an "s" directory, which causes tests to fail due to assumption of Jest being run from a "jest" directory.
  # See packages/jest-message-util/src/index.js PATH_JEST_PACKAGES for more details.
  JEST_DIR: $(Agent.BuildDirectory)/jest

  # Ensures the handful of tests that should be skipped during CI are
  CI: true
