#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

resources:
  repositories:
  - repository: caching-templates
    type: github
    name: willsmythe/caching-templates
    endpoint: willsmythe

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: .azure-pipelines-steps.yml
    variables:
      #CACHE_PACK_TEMP: 'c:\temp\pipelines-caching'
      CACHE_PACK_FORMAT: 7z

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      # This step can be removed once Mercurial gets installed on the macOS image. See https://github.com/Microsoft/azure-pipelines-image-generation/issues/604
      - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install mercurial
        displayName: 'Install Mercurial'
      - template: .azure-pipelines-steps.yml

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # Ensures the handful of tests that should be skipped during CI are
  CI: true

  CACHE_PACK: true
  CACHE_PATH: $(Build.SourcesDirectory)/node_modules
  CACHE_KEY: |
    jest-v9
    node_modules
    $(Agent.OS)
    $(Build.SourcesDirectory)/yarn.lock
    $(CACHE_PACK)
    $(CACHE_PACK_FORMAT)

