#
# Steps for building Jest. See jobs defined in .azure-pipelines.yml
#

steps:
  - checkout: none
    path: jest

  # Ensure Node.js 12 is active
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Use Node.js 12.x'    

  - task: Cache@2
    inputs:
      key: jest | "$(Build.BuildId)" | $(Agent.OS)
      path: $(Pipeline.Workspace)/jest
    displayName: Restore cache

  # Run test-ci-partial
  - script: yarn run test-ci-partial
    displayName: 'Run tests'
    workingDirectory: $(Pipeline.Workspace)/jest

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(Pipeline.Workspace)/jest/**/reports/junit/*.xml'
      testRunTitle: 'CI Tests $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()
