steps:
  - checkout: self
    fetchDepth: 1

  - task: CacheBeta@0
    inputs:
      key: $(Agent.OS)
    continueOnError: true

  - task: CacheBeta@0
    inputs:
      key: yarn.lock
    continueOnError: true   
 
  - task: CacheBeta@0
    inputs:
      key: $(Agent.OS) | jest-test | yarn.lock
    continueOnError: true

  - task: CacheBeta@0
    inputs:
      key: $(Agent.OS) | $(SOME_INVALID) | jest-test | packages/**/package.json | somethingelse
    continueOnError: true
 
  - task: CacheBeta@0
    inputs:
      key: key1 | packages/**/FOOOO__package.json | yarn.lock
    continueOnError: true

  - task: CacheBeta@0
    inputs:
      key: key1 | badfile.txt | packages/**/package.json | ./badfile.txt
    continueOnError: true
  