#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

jobs:
- job: tests
  pool:
    name: Caching2
  steps:
  - checkout: self
    fetchDepth: 1

  - task: CacheBeta@0
    inputs:
      key: $(Agent.OS)
    continueOnError: true
 
  - task: CacheBeta@0
    inputs:
      key: |
        $(Agent.OS)
        jest-test
        yarn.lock
    continueOnError: true

  - task: CacheBeta@0
    inputs:
      key: |
        $(Agent.OS)
        jest-test
        packages/*/package.json
        somethingelse 
    continueOnError: true
 
