#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

resources:
  repositories:
  - repository: caching-templates
    type: github
    name: willsmythe/caching-templates
    endpoint: willsmythe

stages:
- stage: firstrun
  displayName: 'node_modules'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: secondrun
  dependsOn: firstrun
  displayName: 'node_modules CACHED'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: firstrun_pack
  dependsOn: []
  variables:
    CACHE_PACK: true
  displayName: 'node_modules; tar/7z'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: secondrun_pack
  dependsOn: firstrun_pack
  variables:
    CACHE_PACK: true
  displayName: 'node_modules; tar/7z  CACHED'
  jobs:
  - template: .azure-pipelines-jobs.yml

#############
# caching yarn global cache
##############

- stage: firstrun_yarn
  dependsOn: []
  variables:
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/yarn
    CACHE_PATH: $(YARN_CACHE_FOLDER)
  displayName: 'yarn'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: secondrun_yarn
  dependsOn: firstrun_yarn
  variables:
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/yarn
    CACHE_PATH: $(YARN_CACHE_FOLDER)
  displayName: 'yarn CACHED'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: firstrun_yarn_pack  
  dependsOn: []
  variables:
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/yarn
    CACHE_PATH: $(YARN_CACHE_FOLDER)
    CACHE_PACK: true
  displayName: 'yarn; tar/7z'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: secondrun_yarn_pack
  dependsOn: firstrun_yarn_pack
  variables:
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/yarn
    CACHE_PATH: $(YARN_CACHE_FOLDER)
    CACHE_PACK: true
  displayName: 'yarn; tar/7z CACHED'
  jobs:
  - template: .azure-pipelines-jobs.yml

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # Ensures the handful of tests that should be skipped during CI are
  CI: true

  CACHE_PATH: $(Build.SourcesDirectory)/node_modules
  CACHE_KEY: |    
    jest-v10
    node_modules
    $(Agent.OS)
    $(Build.SourcesDirectory)/yarn.lock
    $(CACHE_PACK)
    $(CACHE_PACK_FORMAT)
    $(Build.BuildNumber)
    $(CACHE_PATH)
