#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

stages:
- stage: empty
  displayName: 'Empty'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: cached
  dependsOn: empty
  displayName: 'Cached'
  jobs:
  - template: .azure-pipelines-jobs.yml

- stage: empty_tar
  dependsOn: []
  displayName: 'Empty (tar)'
  jobs:
  - template: .azure-pipelines-jobs.yml
  variables:
    AZP_CACHING_TAR: true

- stage: cached_tar
  dependsOn: empty_tar
  displayName: 'Cached (tar)'
  jobs:
  - template: .azure-pipelines-jobs.yml
  variables:
    AZP_CACHING_TAR: true

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # Ensures the handful of tests that should be skipped during CI are
  CI: true

  CACHE_PATH: $(Build.SourcesDirectory)/node_modules
  CACHE_KEY: jest-v11 | node_modules | $(Agent.OS) | $(Build.SourcesDirectory)/yarn.lock | $(Build.BuildId) | $(AZP_CACHING_TAR)
