#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#

jobs:
- job: caching2
  pool:
    name: Caching2
  steps:
  - template: .azure-pipelines-steps.yml

- job: hosted
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines-steps.yml
