variables:
  # Ensures output from Jest (run during some tests) includes ANSI escape characters so it matches snapshots
  FORCE_COLOR: 1 
  # Default checkout directory is "s", but inline snapshot tests will fail due to assumption that Jest is running under a "jest" folder
  # (see packages/jest-message-util/src/index.js PATH_JEST_PACKAGES)
  JEST_DIR: $(Agent.BuildDirectory)/jest

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: azure-pipelines-steps.yml

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: git config --global core.autocrlf false
    displayName: 'Clone with LF preserved'
  - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
  - script: echo "$(TERM)"
  - template: azure-pipelines-steps.yml
