#
# Azure Pipelines CI configuration for Linux, Windows, and macOS.
#

jobs:
- job: Linux  
  pool:
    vmImage: ubuntu-16.04
  
  steps:
  - template: ci-steps.yml

- job: Windows  
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: git config --global core.autocrlf false
    displayName: 'Clone with LF preserved'
  - template: ci-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
  - script: brew install mercurial
    displayName: 'Install Mercurial'    
  - template: ci-steps.yml
